### PR TITLE
Moved the metadata into setup.cfg

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by nschloe** [comment]
What's all this good for? (Link sufficient.) Do we still have `tikzplotlib.__version__` etc. after this PR?

**Comment by KOLANICH** [comment]
>What's all this good for? (Link sufficient.)

It is a declarative format with rigid schema, rather than executable code. It can be parsed safely. Also it is easier to audit.

>Do we still have `tikzplotlib.__version__` etc. after this PR?

`__version__` - yes, `setuptools_scm` can generate it. The rest of metadata can be fetched via `pkg_resources`. I can create a file fetching them and populating them. But fetching them in runtime will likely not worth: `pkg_resources` is implemented very inefficiently - it iterates the packages. I can also implement generation of that file - but placing any non-trivial code to `setup.py` will defeat the goal of this PR. I really doubt that anyone is using these vars, so IMHO we should just drop them.

**Comment by nschloe** [comment]
For my own reference, let me link this blog post series: https://www.bernat.tech/pep-517-and-python-packaging/.

So yeah, I like the changes, thanks! Can you just remerge master and fix the build error on circleci?

**Comment by nschloe** [comment]
Also, do we need `setup.py` anymore at all?

**Comment by KOLANICH** [comment]
Unfortunately we still do

**Comment by nschloe** [comment]
Closing in favor of https://github.com/nschloe/tikzplotlib/pull/392. (Uses `importlib_metadata` and `tox`.)

**Pull request closed without merging**
