### PR TITLE
fix #405 by ignoring unknown hatch patterns

### LINKED ISSUE #405: Issue with the hatch style option (hatch="" => hatch=None)
Hello,

thanks for a help in advance. I tried your module because i wanna have clean plot in my tex later on. Installing and running of your system worked but dont know which libraries to use because Latex does not tell me which ones are missing. It might be the problem that I am new to tikz but i always think that latex packages hanbooks are not helpfull like in this case too.

Thank you
trixxx3

python code
[graph.txt](https://github.com/nschloe/tikzplotlib/files/4667494/graph.txt)
tex code
[timetable.txt](https://github.com/nschloe/tikzplotlib/files/4667487/timetable.txt)
graph
[timetable.pdf](https://github.com/nschloe/tikzplotlib/files/4667491/timetable.pdf)

### PR DESCRIPTION
**Pull request by Aikhjarto**

### CODE REVIEW

**Comment by nschloe** [comment]
This changes one of test outputs. Can you check if this is correct?

**Comment by Aikhjarto** [comment]
Yes, i noticed the change.
But right now I'm still not sure if my solution is robust. After proposing my my change, I also found `BAD_MP_HATCH ` in _hatches.py and another check for valid hatches in https://github.com/nschloe/tikzplotlib/blob/master/tikzplotlib/_path.py#L286

The BAD_MP_HATCH list in _hatches.py does just maintain a list of patches for which a warning is generated. Am I correct?

**Comment by nschloe** [comment]
Not sure.

**Comment by Aikhjarto** [comment]
I think that I have found the underlying problem and submitted a new pull request.

**Pull request closed without merging**
