### PR TITLE
Inverse axis fix

### PR DESCRIPTION
**Pull request by lukasmu**
Fixed axis direction by conditionally adding options to the axis option array. Fixes two issues as specified in the commit message.

### CODE REVIEW

**Comment by nschloe** [comment]
Could you add a dummy commit to trigger tests?
```
git commit --allow-empty -m "trigger tests"
```
Not sure why they didn't catch on here.

**Comment by lukasmu** [comment]
Done

**Comment by nschloe** [comment]
To make the linter happy, put a `# noqa: C901` to `Axes.__init__`.

**Comment by lukasmu** [comment]
Everything should be fixed now. Not sure if I need to do something about the codecov. Should I add another test?

**Comment by nschloe** [comment]
Nah, it's fine.

**Pull request merged**
